---
title: "IntradayMomentum"
output:
  html_document: default
---

```{r setup, include=TRUE, eval=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```
# Intraday Momentum - `r ticker`

```{r echo=FALSE, warning=FALSE, message = FALSE}
#Clear Workspace
rm(list = ls())

#Source files
source('./libraries.R')
source('./functions.R')

ticker <- 'MSFT'
```

```{r echo = FALSE}
#Load Data
load('../Data/master.Rda')
data <- master[Ticker == ticker]
rm(master)
data[, Ticker := NULL]

#Master data file
data <- na.omit(data)
data <- data[order(Date)]

#Remove outliers abd clean
#Remove outliers for R13
#data <- data[Vol > mean(Vol) - 2*sd(Vol) & Vol < mean(Vol) + 2*sd(Vol)]
```

```{r echo = FALSE}
#Check Date Difference
data[, DayDiff := Date - shift(Date)]
#Check for monday -> 3 difference
data[, Weekday := wday(Date)]

#Remove gaps
data <- data[DayDiff == 1 | (Weekday == 2 & DayDiff == 3)]
```

## Preliminary data analysis
```{r, echo = FALSE, warning=FALSE}
histogram(data$R1, 'First 30-Minute Returns', 'R1')
describe(data$R1)
histogram(data$R13, 'Last 30-Minute Returns', 'R3')
describe(data$R13)
histogram(data$Vol, 'Daily Log Volatility', 'Vol')
describe(data$Vol)
histogram(data$Size, 'Trade Size', 'Size')
describe(data$Size)
```

## Regression
```{r echo = FALSE}
#Combined Columns for 2-variable interaction and higher order terms
#Note: We need to manually create these variables - simply writing X1*X2 in formula won't work
#data[, c('R1_V1', 'R5_V5') := list(R1 * V1, R5 * V5)]
#TODO: Check Xi^2 effects

#R13 = B0 + B1*R1 + B2*R2 + ... + B12*R12
formula <- paste("R13 ~", paste(setdiff(retCols, 'R13'), collapse = " + "))
model <- lm(formula, data = data)
summary(model)
#[Date <= '2014-01-01']

## Newey West Robust T-statistic
#Note: This will not effect R^2 or coefficients - provides adjusted t-statistic
print('Newey West Robust T-statistic')
neweyWest <- coeftest(model, vcov = vcovHC(model))
print(neweyWest)

alphaToEnter <- .08

bestVars <- neweyWest[, 4]
bestVars <- bestVars[bestVars < alphaToEnter] #5% significance
if(length(bestVars[bestVars < alphaToEnter]) < 1) {
  bestVars <- c('R1')
} else {
  bestVars <- names(bestVars[bestVars < alphaToEnter])
}
bestVars <- bestVars[bestVars != "(Intercept)"]
```

## Strategies
```{r}
#Long/Short Strategy
#Predict value
data[, Strat1Signal := predict(model)]
data[, Strat1Ret := ifelse(Strat1Signal > 0, R13, -R13)]
#Note
data <- data[Strat1Ret > mean(Strat1Ret) - 2*sd(Strat1Ret) & Strat1Ret < mean(Strat1Ret) + 2*sd(Strat1Ret)]
data[, Strat1CumRet := cumprod(1 + Strat1Ret)]

#Random Strategy
data[, RandomSignal := rbinom(.N, 1, .5)]
data[, RandomRet := ifelse(Strat1Signal == 1, R13, -R13)]
data[, RandomCumRet := cumprod(1 + RandomRet)]

#Benchmark Hold Strategy
data[, BenchmarkRet := Close / shift(Close) - 1]
data[is.na(BenchmarkRet), BenchmarkRet := 0]
data[, BenchmarkCumRet := cumprod(1 + BenchmarkRet)]
```

## Plot Strategies
```{r echo = FALSE}
#Plot strategies
data <- data[order(Date)]
plot <- ggplot() +
  geom_line(data = data, aes(x = Date, y = BenchmarkCumRet, colour = 'Benchmark Long Strategy')) + 
  geom_line(data = data, aes(x = Date, y = Strat1CumRet, colour = 'Long/Short Strategy')) + 
  geom_line(data = data, aes(x = Date, y = RandomCumRet, colour = 'Random Strategy')) + 
  xlab('Dates') + ylab('Return') + ggtitle('Strategy Return')
plot(plot)
```

## Histogram of Strategy returns
```{r echo = FALSE, warning=FALSE}
histogram(data$BenchmarkRet, 'Benchmark Return', 'BenchmarkRet')
histogram(data$Strat1Ret, 'Long/Short Strategy Daily Returns', 'Strat1Ret')
histogram(data$Strat1Ret - data$BenchmarkRet, 'Excess Daily Returns', 'Excess Returns')
```

## Omit observations with daily volatility oustide 2 and 3 standard devations
```{r echo=FALSE}
data[, c('Strat1Ret_Vol2', 'Strat1Ret_Vol3') := list(Strat1Ret, Strat1Ret)]
data[!(Vol %between% c(mean(Vol) - 2*sd(Vol), mean(Vol) + 2*sd(Vol))), Strat1Ret_Vol2 := 0]
data[!(Vol %between% c(mean(Vol) - 3*sd(Vol), mean(Vol) + 3*sd(Vol))), Strat1Ret_Vol3 := 0]

data[, Strat1_Vol2CumRet := cumprod(1 + Strat1Ret_Vol2)]
data[, Strat1_Vol3CumRet := cumprod(1 + Strat1Ret_Vol3)]

#Plot Long/Hold std modified strategy
plot <- ggplot() +
  geom_line(data = data, aes(x = Date, y = BenchmarkCumRet, colour = 'Benchmark Long Strategy')) + 
  geom_line(data = data, aes(x = Date, y = Strat1CumRet, colour = 'Long/Short Strategy')) + 
  geom_line(data = data, aes(x = Date, y = Strat1_Vol2CumRet, colour = 'Long/Short Strategy +/- 2 Std. Dev. Volatility')) + 
  geom_line(data = data, aes(x = Date, y = Strat1_Vol3CumRet, colour = 'Long/Short Strategy +/- 3 Std. Dev. Volatility')) + 
  xlab('Dates') + ylab('Return') + ggtitle('Strategy Return')
plot(plot)
```

## Histograms of strategies modified by volatility
```{r, echo = FALSE, warning=FALSE}
histogram(data$Strat1Ret - data$BenchmarkRetRet, 'Long/Short Strategy Daily Returns', 'Returns')
describe(data$Strat1Ret - data$BenchmarkRetRet)
histogram(data$Strat1Ret_Vol2 - data$BenchmarkRetRet, 'Long/Short Strategy (+/- 2 Std. Dev. Volatility) Excess Daily Returns', 'Returns')
describe(data$Strat1Ret_Vol2 - data$BenchmarkRetRet)
histogram(data$Strat1Ret_Vol3 - data$BenchmarkRetRet, 'Long/Short Strategy (+/- 3 Std. Dev. Volatility) Excess Daily Returns', 'Returns')
describe(data$Strat1Ret_Vol3 - data$BenchmarkRetRet)
```


```{r, echo=FALSE, warning=FALSE}
#Rolling Regression Data
#250 trading days a year * 3 years
lookback <- 250*5

rollRegCols <- c('Date', setdiff(retCols, 'R13'), 'Type', 'Lookback')
rollRegVars <- data.frame()
for (c in rollRegCols) rollRegVars[[c]] <- as.character()

rollModelPerf <- data.frame(Date = as.character(), AdjRSquared = as.numeric(), 
                            ResidualStdErr = as.numeric(), Lookback = as.logical(), stringsAsFactors = FALSE)

#Apply rolling regression
for(date in data[Date >= min(Date) + lookback, Date]) {
  date <- as.Date(date)
  temp <- rollRegressFunc(data[Date <= date & Date > date - lookback], isLookback = TRUE, setdiff(retCols, 'R13'))
  rollRegVars <- rbind(rollRegVars, temp[[1]])
  rollModelPerf <- rbind(rollModelPerf, temp[[2]])
  temp <- rollRegressFunc(data[Date <= date], isLookback = FALSE, setdiff(retCols, 'R13'))
  rollRegVars <- rbind(rollRegVars, temp[[1]])
  rollModelPerf <- rbind(rollModelPerf, temp[[2]])
}

rollRegVars[, Date := as.Date(Date)]
rollRegVars[, Lookback := as.logical(Lookback)]
rollRegVars[, (setdiff(retCols, 'R13')) := lapply(.SD, as.numeric), .SDcols = setdiff(retCols, 'R13')]
rollModelPerf[, Date := as.Date(Date)]
```


## Rolling Regression
### Lookback
```{r echo = FALSE}
temp <- melt(rollRegVars, id.vars = c('Date', 'Lookback', 'Type'), measure.vars = bestVars) %>% data.table()

#Coefficients
plot <- ggplot(data = temp[Type == 'Coeff' & Lookback == TRUE], 
               aes(x = Date, y = value, group = variable, color = variable)) + geom_line() + 
  xlab('Dates') + ylab('Coefficient') + ggtitle('Regression Coefficients')
plot(plot)

#P-Values
plot <- ggplot(data = temp[Type == 'PVal' & Lookback == TRUE], 
               aes(x = Date, y = value, group = variable, color = variable)) + geom_line() + 
  xlab('Dates') + ylab('P-Value') + ggtitle('P-Value')
plot(plot)

#Adjusted R-Squared
plot <- ggplot() +
  geom_line(data = rollModelPerf[Lookback == TRUE], aes(x = Date, y = AdjRSquared, colour = 'R^2')) + 
  xlab('Dates') + ylab('R^2') + ggtitle('Adjusted R-Squared')
plot(plot)

#Residual Standard Error
plot <- ggplot() +
  geom_line(data = rollModelPerf[Lookback == TRUE], aes(x = Date, y = ResidualStdErr, colour = 'Error')) + 
  xlab('Dates') + ylab('Error') + ggtitle('Standard Error of Residuals')
plot(plot)
```

### Complete History
```{r echo = FALSE}
temp <- melt(rollRegVars, id.vars = c('Date', 'Lookback', 'Type'), measure.vars = bestVars) %>% data.table()

#Coefficients
plot <- ggplot(data = temp[Type == 'Coeff' & Lookback == FALSE], 
               aes(x = Date, y = value, group = variable, color = variable)) + geom_line() + 
  xlab('Dates') + ylab('Coefficient') + ggtitle('Regression Coefficients')
plot(plot)

#P-Values
plot <- ggplot(data = temp[Type == 'PVal' & Lookback == FALSE], 
               aes(x = Date, y = value, group = variable, color = variable)) + geom_line() + 
  xlab('Dates') + ylab('P-Value') + ggtitle('P-Value')
plot(plot)

#Adjusted R-Squared
plot <- ggplot() +
  geom_line(data = rollModelPerf[Lookback == FALSE], aes(x = Date, y = AdjRSquared, colour = 'R^2')) + 
  xlab('Dates') + ylab('R^2') + ggtitle('Adjusted R-Squared')
plot(plot)

#Residual Standard Error
plot <- ggplot() +
  geom_line(data = rollModelPerf[Lookback == FALSE], aes(x = Date, y = ResidualStdErr, colour = 'Error')) + 
  xlab('Dates') + ylab('Error') + ggtitle('Standard Error of Residuals')
plot(plot)
```